FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml* pnpm-workspace.yaml* ./
RUN pnpm install --prod --frozen-lockfile --ignore-scripts

COPY . .

ENV NODE_ENV=production

EXPOSE 3000

CMD ["node", "index.js"]
