// <auto-generated />
using System;
using AuthService.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthService.Persistence.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("AuthService.Domain.Entities.Role", b =>
        {
            b.Property<int>("IdRol")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("id_rol");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

            b.Property<string>("Nombre")
                .IsRequired()
                .HasMaxLength(35)
                .HasColumnType("character varying(35)")
                .HasColumnName("nombre");

            b.HasKey("IdRol")
                .HasName("pk_roles");

            b.ToTable("roles");
        });

        modelBuilder.Entity("AuthService.Domain.Entities.User", b =>
        {
            b.Property<int>("IdUsuario")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("id_usuario");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

            b.Property<string>("Nombre")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("nombre");

            b.Property<string>("Apellido")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("apellido");

            b.Property<string>("Correo")
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnType("character varying(150)")
                .HasColumnName("correo");

            b.Property<string>("Contrasena")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("character varying(255)")
                .HasColumnName("contrasena");

            b.Property<DateTime>("FechaRegistro")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("fecha_registro");

            b.Property<int>("IdRol")
                .HasColumnType("integer")
                .HasColumnName("id_rol");

            b.HasKey("IdUsuario")
                .HasName("pk_usuarios");

            b.HasIndex("Correo")
                .IsUnique()
                .HasDatabaseName("ix_usuarios_correo");

            b.HasIndex("IdRol")
                .HasDatabaseName("ix_usuarios_id_rol");

            b.ToTable("usuarios");
        });

        modelBuilder.Entity("AuthService.Domain.Entities.User", b =>
        {
            b.HasOne("AuthService.Domain.Entities.Role", "Rol")
                .WithMany("Usuarios")
                .HasForeignKey("IdRol")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Rol");
        });

        modelBuilder.Entity("AuthService.Domain.Entities.Role", b =>
        {
            b.Navigation("Usuarios");
        });
#pragma warning restore 612, 618
    }
}
